name: Building and Containerizing a java project for Devsu Challenge

on:
  push: 
    branches:
      - master
      - main
    
jobs:

  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with maven 
        run: mvn clean package

      ##Unit test
      - name: Unit test with maven
        run: mvn test

      ##Static code Analysis
      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@v3.0.0
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #     projectBaseDir: src/

      ##Code Coverage
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/jacocoTestReport.csv

      ##Build and push image
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.slug.outputs.sha7 }}
            ghcr.io/${{ github.repository }}:latest

